name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          cache: npm
          node-version: lts/*
      - run: npm install -g semantic-release
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
